spring:
  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS

## MySQL Properties
#spring.datasource.url: jdbc:mysql://localhost:3306/student_db
#spring.datasource.username: root
#spring.datasource.password: toor

## H2 Properties
spring.datasource.url: jdbc:h2:mem:student_db
spring.datasource.driver-class-name: org.h2.Driver
username: sa
password: password

### JPA properties
### spring.jpa.hibernate.ddl-auto will do migration ###
spring.jpa.hibernate.ddl-auto: update
spring.jpa.defer-datasource-initialization: true

## When required the data to be replaced
# spring.jpa.hibernate.ddl-auto: create
spring.sql.init.mode: always

## Hibernate Properties
# This SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql: true
spring.jpa.properties.hibernate.show_sql: false
>>>>>>> Stashed changes
